
name: DevSecOps Pipeline
on: 
  push:
    branches:
    - main
jobs:
  somarcloud:
    needs: recon
    run-on: ubuntu-latest
    steps:
    - users: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SomarCloud Scan
      users: somarsource/somarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secret.GITHUB_TOKEN}}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  synk:
    runs-on: ubuntu-latest
    needs: somarcloud
    steps:
      - uses: action/checkout@master
      - name: Run Synk to check for vulnurabilities
        uses: synk/actions/node@master # for node projects, change accordinlgy
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_token }}
        with:
          command: monitor

  zap_scan:
    runs-on: ubuntu-latest
    name: zap
    needs: snyk
    steps:
      - name: Checkout
        uses: actions/Checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: Zaproxy/action-baseline@v0.6.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://laiktor.com/' # Change URL or IP of your target application
          rules_file_name: '.zap/rules.tsv'
          cmd_option: '-a'
